### ISSUE TITLE
Databáza - porovnať réalnu verziu DB a dokumentáciu z 2017 a vytvoriť UML súčasného stavu DB

### ISSUE THREAD

**Issue by Kirito-chan** [Kirito-chan/cogsci-lms#4]

**Comment by crnkjck** [comment]
* [x] Vytvoriť UML reálnej štruktúry DB

**Comment by Kirito-chan** [comment]
Uz som vytvoril UML sucasnej verzzie databazy: https://drive.google.com/file/d/1ZRmV5Fk6yk_LJdHg8-iCAauST5PnV-Q5/view?usp=sharing

A tu su v kratkosti hlavne rozdiely:
_________________
_**Realna DB**_

**1. chyba stlpec: _response_to_id_**
- v dokumentacii 2017 sa nachadza v tabulkach: _"user_presentation_comments", "announcements_comments", "teacher_presentation_comments"_
_________________________________________________________________________________________________________________________
**2.  tabulka _"user_subject_lookup"_ je v realnej DB, aj v UML diagrame dokumentacie, ale nie v popise dokumentacie a nahradza tabulku "subject_user", ktora uz momentalne neexistuje v realnej DB - sice je tabulka "subject_user" vytvorena v realnej DB, ale nie je naplnena**
_____________________
**3.  chyba tabulka: _"user_subject_presentation_lookup"_**
- vobec nie je v realnej databaze, iba na obrazku UML v specifikacii
_____________________
**4. a 5. v tabulke _"teacher_presentation"_ chyba stlpec _"user_id"_ a zaroven je v tejto tabulke naviac stlpec _"date"_ oproti dokumentacii 2017**
