### ISSUE TITLE
Naučiť sa základy backendu

### ISSUE THREAD

**Issue by crnkjck** [Kirito-chan/cogsci-lms#5]
* PERN - Postgres, Express, React, and Node
  „Full-stack“ kombinácia front- a back-endových technológií pri vývoji webovej aplikácie
  Tutoriál od freecodecamp: https://www.youtube.com/watch?v=ldYcgPKEZC8
* https://expressjs.com/
* Pozrieť API frameworky postavené na ExpressJS: https://expressjs.com/en/resources/frameworks.html

**Comment by Kirito-chan** [comment]
Pozrel som si tutoriál od freecodecamp: https://www.youtube.com/watch?v=ldYcgPKEZC8
a tiez aj na expressJS tento tutorial: https://www.youtube.com/watch?v=pKd0Rpw7O48&ab_channel=ProgrammingwithMosh

A rozhodol som sa pouzivat expressJS ako backend, hoci aj ine frameworky zalozene na expresse by mohli byt zaujimave, no s expressom si vystacim.
